@host =  http://localhost
@port = 3000
@apiAdmins = /api/admins
@apiUsuarios = /api/usuarios
@apiProyectos = /api/proyectos
@apiDepartamentos = /api/departamentos

###
GET {{host}}:{{port}}{{apiAdmins}}

###
PUT {{host}}:{{port}}{{apiAdmins}}/2
Content-Type: application/json

{
    "nombre": "Juan",
    "apellidos": "Lopez",
    "email": "juanlopez@hotmail.com",
    "password":132465
  }

###
POST {{host}}:{{port}}{{apiAdmins}}/registro
Content-Type: application/json

{
    "nombre": "test132",
    "apellidos": "Jose",
    "email": "test132@hotmail.com",
    "password":"123456798"
}

###
POST {{host}}:{{port}}{{apiAdmins}}/login
Content-Type: application/json

{
    "email": "test132@hotmail.com",
    "password":"123456798"
}

###
GET http://localhost:3000/api/usuarios/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJleHAiOjE2OTA5Njk0NDEsImlhdCI6MTY4OTY3MzQ0MX0.6qDC-8xNIQJZxQwbGpt8r7SAePzXy4Dhi3q4J54oYqM

###
DELETE {{host}}:{{port}}{{apiAdmins}}/2

#########################
##   API USUARIOS     ##
#########################

###
GET {{host}}:{{port}}{{apiUsuarios}}
Authorization: 

###
GET {{host}}:{{port}}{{apiUsuarios}}/6
Authorization: 

###
GET {{host}}:{{port}}{{apiUsuarios}}/10/fecha/2023-07-17
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJleHAiOjE2OTA5Njk0NDEsImlhdCI6MTY4OTY3MzQ0MX0.6qDC-8xNIQJZxQwbGpt8r7SAePzXy4Dhi3q4J54oYqM

###
POST {{host}}:{{port}}{{apiUsuarios}}
Content-Type: application/json

{
  "nombre": "claudia",
  "apellidos": "lopez",
  "dni": "71206753n",
  "email": "claudiaaaa@gmail.com",
  "password":"123456",
  "telefono": 666778886,
  "estado":1,
  "fecha_alta": "2023-03-27",
  "departamento_id":"2"
  
}

###
PUT {{host}}:{{port}}{{apiUsuarios}}/251
Content-Type: application/json

{
  "nombre": "claudia",
  "apellidos": "lopez",
  "dni": "71206773n",
  "email": "claudialopez@gmail.com",
  "password":"123456",
  "telefono": 666668886,
  "estado":1,
  "fecha_alta": "2023-03-27",
  "departamento_id":"1"
  
}
###
DELETE {{host}}:{{port}}{{apiUsuarios}}/251

#########################
##    API PROYECTOS    ##
#########################

###
GET {{host}}:{{port}}{{apiProyectos}}
Authorization: 

###
PUT {{host}}:{{port}}{{apiProyectos}}/3
Content-Type: application/json

{
    "nombre": "test888",
    "descripcion": "Test123888"
  }

###
POST {{host}}:{{port}}{{apiProyectos}}
Content-Type: application/json

{
    "nombre": "test456",
    "descripcion": "Test12345"
  }

###
DELETE {{host}}:{{port}}{{apiProyectos}}/5

#########################
##  API DEPARTAMENTOS  ##
#########################
###
GET {{host}}:{{port}}{{apiDepartamentos}}

###
PUT {{host}}:{{port}}{{apiDepartamentos}}
###
POST {{host}}:{{port}}{{apiDepartamentos}}

###
DELETE {{host}}:{{port}}{{apiDepartamentos}}
